name: tox

on:
  create: # is used for publishing to PyPI and TestPyPI
    tags: # any tag regardless of its name, no branches
      - "**"
  push: # only publishes pushes to the main branch to TestPyPI
    branches: # any integration branch but not tag
      - "main"
  pull_request:

jobs:
  unit:
    name: ${{ matrix.name || matrix.tox_env }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    defaults:
      run:
        shell: ${{ matrix.shell || 'bash'}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
        name:
          - wsl-2022
        shell:
          - "wsl-bash {0}"

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # needed by setuptools-scm

      - name: Activate WSL1
        if: "contains(matrix.shell, 'wsl')"
        uses: Vampire/setup-wsl@v1

      - name: Install tools
        run: |
          sudo apt-get remove -y ansible pipx || true
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends -o=Dpkg::Use-Pty=0 git python3-venv python3-pip
          pip3 install ansible-core
          ansible --version

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 45
        with:
          limit-access-to-actor: true
